name: build and push multi arch images
on: workflow_dispatch

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'v2.2.1'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build tools docker image (with buildx)
        run: |
          docker build -f images/tools/Dockerfile --build-arg GO_VER=1.14.4 --build-arg ALPINE_VER=3.13 --build-arg GO_TAGS= --platform linux/amd64,linux/arm64 -t mirioeggmann/fabric-tools:2.2.1  --push . 
      - name: Build baseos docker image (with buildx)
        run: |
          docker build -f images/baseos/Dockerfile --build-arg GO_VER=1.14.4 --build-arg ALPINE_VER=3.13 --platform linux/amd64,linux/arm64 -t mirioeggmann/fabric-baseos:2.2.1  --push . 
      - name: Build ccenv docker image (with buildx)
        run: |
          docker build -f images/ccenv/Dockerfile --build-arg GO_VER=1.14.4 --build-arg ALPINE_VER=3.13 --platform linux/amd64,linux/arm64 -t mirioeggmann/fabric-ccenv:2.2.1  --push . 
      - name: Build orderer docker image (with buildx)
        run: |
          docker build -f images/orderer/Dockerfile --build-arg GO_VER=1.14.4 --build-arg ALPINE_VER=3.13 --build-arg GO_TAGS= --platform linux/amd64,linux/arm64 -t mirioeggmann/fabric-orderer:2.2.1  --push . 
      - name: Build peer docker image (with buildx)
        run: |
          docker build -f images/peer/Dockerfile --build-arg GO_VER=1.14.4 --build-arg ALPINE_VER=3.13 --build-arg GO_TAGS= --platform linux/amd64,linux/arm64 -t mirioeggmann/fabric-peer:2.2.1  --push . 
