name: build and push multi arch images
on: push

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Run Buildx
        run: |
          docker buildx build -f images/tools/Dockerfile --build-arg GO_VER=1.15.7 --build-arg ALPINE_VER=3.13 --platform linux/amd64,linux/arm64,linux/arm/v7 -t mirioeggmann/fabric-tools:latest --push . 
